### PR TITLE
Do not try to recreate Metrics Thread if initialization failed

### LINKED ISSUE #172: Metrics Reporter Thread initialization breaks application
### Background information

Due to a dependency conflict in an application, we started seeing errors originating from the tracer's `span.finish()` method. See exception below:

```
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.internal.concurrent.TaskRunner
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:445)
	at com.lightstep.tracer.metrics.OkHttpSender.start(OkHttpSender.java:74)
	at com.lightstep.tracer.metrics.OkHttpSender.<init>(OkHttpSender.java:32)
	at com.lightstep.tracer.metrics.SafeMetricsImpl.createMetricsThread(SafeMetricsImpl.java:20)
	at com.lightstep.tracer.shared.AbstractTracer.maybeStartReporting(AbstractTracer.java:264)
	at com.lightstep.tracer.shared.AbstractTracer.addSpan(AbstractTracer.java:649)
	at com.lightstep.tracer.shared.Span.finish(Span.java:62)
	at com.lightstep.tracer.shared.Span.finish(Span.java:46)
	at io.opentracing.contrib.web.servlet.filter.TracingFilter$1.onComplete(TracingFilter.java:215)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnComplete(AsyncListenerWrapper.java:39)
	at org.apache.catalina.core.AsyncContextImpl.fireOnComplete(AsyncContextImpl.java:104)
	at org.apache.coyote.AsyncStateMachine.asyncPostProcess(AsyncStateMachine.java:290)
	at org.apache.coyote.AbstractProcessor.asyncPostProcess(AbstractProcessor.java:195)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:80)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

The 
`java.lang.NoClassDefFoundError` exception was caused by a conflict with Kotlin libraries.
okhttp has 1.3.61 as dependency, but the application was overriding it with 1.2.72 due to another transitive dependency in Spring Boot 2.1.3, and fixed by pinning the Kotlin version to 1.3.x

```
[INFO] +- com.lightstep.tracer:lightstep-tracer-jre:jar:0.30.1:compile
[INFO] |  +- com.lightstep.tracer:java-common:jar:0.30.0:compile
[INFO] |  |  +- io.opentracing:opentracing-api:jar:0.33.0:compile
[INFO] |  |  +- io.opentracing:opentracing-util:jar:0.33.0:compile
[INFO] |  |  |  \- io.opentracing:opentracing-noop:jar:0.33.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.9.0:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-common-protos:jar:1.17.0:compile
[INFO] |  +- com.lightstep.tracer:java-metrics-reporter:jar:0.1.4:compile
[INFO] |  |  +- com.github.oshi:oshi-core:jar:4.4.2:compile
[INFO] |  |  |  +- net.java.dev.jna:jna:jar:5.5.0:compile
[INFO] |  |  |  \- net.java.dev.jna:jna-platform:jar:5.5.0:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:4.3.1:compile
[INFO] |  |     +- com.squareup.okio:okio:jar:2.4.1:compile
[INFO] |  |     |  \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.50:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.61:compile
[INFO] |  |        \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
```

### Problem Description

What I wanted to raise with this issue was that the exception had as a side effect errors in the application itself. Even though the business logic was correctly processed, the application ended up returning an error because of that exception when finishing the span.

Fortunately, the exception happened when creating the Metrics Reporter thread, which is after the Span was finished, and the Span Reporter thread was already created and shipped the spans to the satellites (meaning no memory leak caused by unfinished spans, and no dropped spans on the client).
Although this also resulted in misleading tracing data, as the span that was finished and exported reported a successful operation as the failure happened after the span was finished.

### Further details

The exception's stacktrace points to the problem coming from here: [SafeMetricsImpl.java#L20][1].
The code in SafeMetricsImpl is called from the [Tracer implementation][2] when it attempts to push tracing and metrics data.
Notice how the `metricsThread` is initialized after the `reporterThread`. This detail is relevant because, despite an exception in the Tracing instrumentation, we still had spans shipped to the Tracing satellites, and from there to the LightStep backend.

What controls whether or not the threads are initialized is the [existence of a reporterThread][3]. That thread is only discarded when the tracer is shutdown, or when the [tracer has no tracing data to report][4].
The tracer is more likely to have no tracing data to report in a low throughput situation, which is precisely when we faced the issue, even though it was in production for some time before.

### Expected Behavior

The expected behavior is that any failure in the tracing implementation does not affect the application logic.
It's good to see that spans are finished before any of the thread initialization to prevent a memory leak, but the initialization code itself should be further isolated to prevent such issues, while logging the error to make sure it does not go completely unnoticed.
This could be achieved by a catch all exception on the thread initialization code, or by validating that threads can be initialized at the time the Tracer is instantiated and fail there, leaving application owners to decide whether application should fail to start, or fall back to a NoopTracer.

Further, the Span reporter thread clearly has more relevance as it is used to determine whether or not both threads should be initialized. However, any issues initializing the metrics thread can break the calling application, while not having an effect on any of the other tasks performed in the `span.finish()` method. This behavior does not seem consistent, but I could just be misreading it. Any clarification is welcome.

Looking forward to hearing your thoughts on this issue.

[1]: https://github.com/lightstep/lightstep-tracer-java/blob/c24e7b9e4b86bde02cedb31b434caf7ea7b512d1/lightstep-tracer-jre/src/main/java/com/lightstep/tracer/metrics/SafeMetricsImpl.java#L20
[2]: https://github.com/lightstep/lightstep-tracer-java-common/blob/d50b6a759503d5eb34d0a89bc5bb57d7da9586e8/common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java#L244
[3]: https://github.com/lightstep/lightstep-tracer-java-common/blob/d50b6a759503d5eb34d0a89bc5bb57d7da9586e8/common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java#L246
[4]: https://github.com/lightstep/lightstep-tracer-java-common/blob/d50b6a759503d5eb34d0a89bc5bb57d7da9586e8/common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java#L331

### PR DESCRIPTION
**Pull request by malafeev**
fix #172

### CODE REVIEW

File: common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java [hunk 1]
```diff
@@ -259,14 +260,23 @@ private void maybeStartReporting() {
...
-          }
+        if (!disableMetricsReporting && safeMetrics != null && !metricsThreadInitializationFailed) {
+            try {
+                metricsThread = safeMetrics
+                    .createMetricsThread(componentName, auth.getAccessToken(),
+                        serviceVersion, metricsUrl,
+                        LightStepConstants.Metrics.DEFAULT_INTERVAL_SECS);
+            } catch (Throwable e) {
+                // Can be due to dependency conflict e.g. Kotlin libs.
+                warn("Failed to initialize Metrics thread, new initialization will not be retried.",
```
Comment (carlosalberto) [inline common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java:271]: Can we go for `error()` instead?

**Review by carlosalberto — APPROVED** [review]

File: common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java (hunk 1 above)
Comment (malafeev) [reply common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java]: done
